const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env') });
const express = require('express');
const cors = require('cors');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// ─── FULL MERN: MONGODB CONNECTION ───
const mongoose = require('mongoose');
// Fallback to local MongoDB if MONGO_URI is not set in .env
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/orbitalresq';

mongoose.connect(MONGO_URI)
  .then(() => console.log('✅ Connected to MongoDB (MERN Stack Complete)'))
  .catch(err => console.log('⚠️ MongoDB not running locally, skipping database logs.'));

// Schema to save Copilot Chat Logs
const ChatLogSchema = new mongoose.Schema({
  question: String,
  answer: String,
  timestamp: { type: Date, default: Date.now }
});
const ChatLog = mongoose.model('ChatLog', ChatLogSchema);

// Serve static map assets (PNGs and GeoJSONs generated by our pipeline)
app.use('/static', express.static(path.join(__dirname, 'public')));

// ─── API: Map Config ───
app.get('/api/config', (req, res) => {
    try {
        const bounds = require('./public/bounds.json');
        res.json({
            status: 'success',
            project: 'OrbitalResQ',
            bounds: bounds,
            layers: {
                floodOverlay: '/static/flood_overlay.png',
                buildings: '/static/damaged_buildings.geojson',
                roads: '/static/damaged_roads.geojson'
            }
        });
    } catch (error) {
        res.status(500).json({ status: 'error', message: 'Map bounds not found.' });
    }
});

// ─── API: Situation Report Stats ───
app.get('/api/sitrep', (req, res) => {
    try {
        const statsPath = path.join(__dirname, '..', '..', 'data', 'processed', 'sitrep_stats.json');
        const stats = JSON.parse(fs.readFileSync(statsPath, 'utf-8'));
        res.json({ status: 'success', stats });
    } catch (error) {
        res.status(500).json({ status: 'error', message: 'Sitrep stats not found. Run report_generator.py first.' });
    }
});

// ─── API: Situation Report Text ───
app.get('/api/sitrep/:lang', (req, res) => {
    const lang = req.params.lang === 'ne' ? 'nepali' : 'english';
    try {
        const reportPath = path.join(__dirname, '..', '..', 'data', 'processed', `sitrep_${lang}.txt`);
        const report = fs.readFileSync(reportPath, 'utf-8');
        res.json({ status: 'success', language: lang, report });
    } catch (error) {
        res.status(500).json({ status: 'error', message: `${lang} report not found.` });
    }
});

// ─── API: Copilot Chat (Grounded in Map Data) ───
app.post('/api/copilot', async (req, res) => {
    const { question } = req.body;
    if (!question) {
        return res.status(400).json({ status: 'error', message: 'No question provided.' });
    }

    // Load the grounding data (all numbers from our pipeline)
    let stats = {};
    let enReport = '';
    try {
        const statsPath = path.join(__dirname, '..', '..', 'data', 'processed', 'sitrep_stats.json');
        stats = JSON.parse(fs.readFileSync(statsPath, 'utf-8'));
        const reportPath = path.join(__dirname, '..', '..', 'data', 'processed', 'sitrep_english.txt');
        enReport = fs.readFileSync(reportPath, 'utf-8');
    } catch (e) {
        return res.status(500).json({ status: 'error', message: 'Pipeline data not found.' });
    }

    const GEMINI_KEY = process.env.GEMINI_API_KEY;

    if (GEMINI_KEY) {
        // ─── LLM-Powered Copilot (Gemini) ───
        try {
            const { GoogleGenerativeAI } = require('@google/generative-ai');
            const genAI = new GoogleGenerativeAI(GEMINI_KEY);
            const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

            const systemPrompt = `You are OrbitalResQ Copilot, a disaster response assistant for the August 2026 Nepal flood.
You help rescue teams by answering questions about flood damage.

CRITICAL RULES:
1. Every number you quote MUST come from the DATA below. NEVER invent or hallucinate numbers.
2. If the data doesn't contain the answer, say "This information is not available in our current analysis."
3. Keep answers concise and actionable for field rescue teams.
4. You can respond in English or Nepali based on the user's language.

=== GROUNDING DATA (from satellite analysis) ===
${JSON.stringify(stats, null, 2)}

=== FULL SITUATION REPORT ===
${enReport}
=== END DATA ===`;

            const result = await model.generateContent({
                contents: [
                    { role: 'user', parts: [{ text: systemPrompt + '\n\nRescuer question: ' + question }] }
                ]
            });
            const answer = result.response.text();
            
            // Save to MongoDB
            try { await ChatLog.create({ question, answer }); } catch(e) {}

            return res.json({ status: 'success', answer, source: 'gemini' });
        } catch (e) {
            console.error('Gemini error:', e.message);
            // Fall through to template-based
        }
    }

    // ─── Template-Based Fallback (No API Key Needed) ───
    const q = question.toLowerCase();
    let answer = '';

    if (q.includes('flood') && (q.includes('area') || q.includes('extent') || q.includes('size') || q.includes('how much'))) {
        answer = `Based on our satellite analysis, the estimated flood extent is ${stats.flood_area_km2 || 0} km². Standing water covers ${stats.water_area_km2 || 0} km² and debris/mud deposits cover ${stats.debris_area_km2 || 0} km². This was detected using ${stats.flooded_pixels?.toLocaleString() || 0} flooded pixels out of ${stats.total_pixels?.toLocaleString() || 0} total pixels analyzed (${stats.flood_percent || 0}% of the area).`;
    } else if (q.includes('building') || q.includes('house') || q.includes('structure')) {
        answer = `Our analysis identified ${stats.damaged_buildings || 0} buildings affected by the flood. This estimate is based on intersecting the AI-generated flood mask with pre-event OpenStreetMap building footprints (snapshot: 2026-07-27).`;
    } else if (q.includes('road') || q.includes('bridge') || q.includes('highway')) {
        answer = `${stats.damaged_roads || 0} road segments were detected as flooded or blocked by debris. Road damage was determined by overlaying the flood mask on the pre-event OpenStreetMap road network.`;
    } else if (q.includes('cut off') || q.includes('isolated') || q.includes('village') || q.includes('stranded') || q.includes('disconnect')) {
        const names = stats.cutoff_village_names?.length > 0 ? ` The affected villages are: ${stats.cutoff_village_names.join(', ')}.` : '';
        answer = `${stats.cutoff_villages || 0} villages have lost their road connection to the nearest town or hospital.${names} These villages were identified by removing flooded road segments from the network graph and checking for disconnected settlements.`;
    } else if (q.includes('water') || q.includes('debris') || q.includes('mud')) {
        answer = `The AI classified the flood into two categories: Standing water covering ${stats.water_area_km2 || 0} km² (${stats.water_pixels?.toLocaleString() || 0} pixels), and debris/mud deposits covering ${stats.debris_area_km2 || 0} km² (${stats.debris_pixels?.toLocaleString() || 0} pixels).`;
    } else if (q.includes('date') || q.includes('when') || q.includes('time')) {
        answer = `The pre-event satellite image was acquired on ${stats.pre_date || 'N/A'} and the post-event image on ${stats.post_date || 'N/A'}. The flood event occurred on 26 August 2026 following a glacier collapse in northern Nepal.`;
    } else if (q.includes('location') || q.includes('where') || q.includes('coordinate') || q.includes('center')) {
        answer = `The analysis is centered at ${stats.center_lat || 'N/A'}°N, ${stats.center_lon || 'N/A'}°E, covering the Bhote Koshi–Trishuli river corridor in Nepal.`;
    } else if (q.includes('help') || q.includes('what can you')) {
        answer = `I can answer questions about: flood extent and area, damaged buildings, flooded roads, cut-off villages, water vs debris classification, event dates, and analysis location. All my answers are grounded in satellite data — I never invent numbers.`;
    } else {
        answer = `Based on our satellite analysis: The flood affected an area of ${stats.flood_area_km2 || 0} km², damaging ${stats.damaged_buildings || 0} buildings and ${stats.damaged_roads || 0} road segments. ${stats.cutoff_villages || 0} villages lost road access. For more specific information, try asking about "flood area", "damaged buildings", "cut-off villages", or "road damage".`;
    }

    res.json({ status: 'success', answer, source: 'template' });
});

app.listen(PORT, () => {
    console.log(`OrbitalResQ Backend running on http://localhost:${PORT}`);
});
