const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Serve static map assets (PNGs and GeoJSONs generated by our pipeline)
app.use('/static', express.static(path.join(__dirname, 'public')));

// Mongoose connection (Optional for this specific raster dashboard, but standard for MERN)
/*
mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/orbitalresq', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).then(() => console.log('MongoDB Connected'))
  .catch(err => console.log('MongoDB connection error:', err));
*/

// API Endpoint to get project metadata and map configuration
app.get('/api/config', (req, res) => {
    try {
        const bounds = require('./public/bounds.json');
        res.json({
            status: 'success',
            project: 'OrbitalResQ',
            bounds: bounds,
            layers: {
                floodOverlay: '/static/flood_overlay.png',
                buildings: '/static/damaged_buildings.geojson',
                roads: '/static/damaged_roads.geojson'
            }
        });
    } catch (error) {
        res.status(500).json({ status: 'error', message: 'Map bounds not found. Ensure pipeline ran.' });
    }
});

app.listen(PORT, () => {
    console.log(`Backend server running on http://localhost:${PORT}`);
});
